// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbuwbvusrlbdshmaxxso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidXdidnVzcmxiZHNobWF4eHNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTI2NDksImV4cCI6MjA2NTQ4ODY0OX0.LZ8hofg_HQERedImaTrbC_uE_iqqqyrONMd3Ca3MjGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);